---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yml

  tasks:
    # TODO replace os_* module
    - name: Get compute imaging instance information
      os_server_info:
        server: "{{ cluster_name }}-compute-imaging"
      register: server_info

    - name: Detach floating IP from compute imaging instance
      openstack.cloud.floating_ip:
        cloud: "{{ cloud_name }}"
        state: absent
        floating_ip_address: "{{ server_info.openstack_servers[0].public_v4 }}"
        network: "{{ cluster_network_floating_ip_pool }}"
        server: "{{ cluster_name }}-compute-imaging"
      when: server_info.openstack_servers[0] is defined

    - name: Shut down compute imaging instance
      openstack.cloud.server_action:
        cloud: "{{ cloud_name }}"
        server: "{{ cluster_name }}-compute-imaging"
        action: stop
      when: server_info.openstack_servers[0] is defined

    - name: Delete compute imaging instance
      openstack.cloud.server:
        name: "{{ cluster_name }}-compute-imaging"
        state: absent

    - name: Wait for the compute image volume is detached
      openstack.cloud.volume_info:
        name: "{{ compute_node_image }}"
        details: true
      register: volumes_info
      until: volumes_info.volumes[0].status is match("available")

    - name: Delete compute image
      openstack.cloud.image:
        name: "{{ compute_node_image }}"
        state: absent

    - name: Create compute image
      openstack.cloud.image:
        name: "{{ compute_node_image }}"
        volume: "{{ volumes_info.volumes[0].id }}"
        #visibility: private
        is_public: false
        disk_format: raw
        timeout: 1200
        state: present

    - name: Delete compute image volume
      openstack.cloud.volume:
        name: "{{ volumes_info.volumes[0].id }}"
        state: absent

    - debug:
        msg: "Created {{ compute_node_image }}."
