---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yml

  tasks:
    - name: Get head node information
      os_server_info:
        server: "{{ cluster_name }}-compute-imaging"
      register: server_info
#
#    - name: Detach floating IP from headnode
#      openstack.cloud.floating_ip:
#        cloud: "{{ cloud_name }}"
#        state: absent
#        floating_ip_address: "{{ server_info.openstack_servers[0].public_v4 }}"
#        network: "{{ cluster_network_floating_ip_pool }}"
#        server: "{{ cluster_name }}-compute-imaging"
#
#    - name: Shut down compute imaging instance
#      openstack.cloud.server_action:
#        cloud: "{{ cloud_name }}"
#        server: "{{ cluster_name }}-compute-imaging"
#        action: stop
#

  # TODO: check if "{{ cluster_name }}-compute-image" (compute_node_image) is really needed

    - name: Delete compute node image volume
      openstack.cloud.volume:
        name: "{{ compute_node_image }}"
        state: absent

    - debug:
        var: server_info

    - meta: end_play

# TODO: check if this below is really openstack.cloud.image with original repo

    - name: Create compute image
      openstack.cloud.image:
        name: "{{ compute_node_image }}"
        volume: "{{ volumes_info.volumes[0].id }}"
        disk_format: raw
        timeout: 1200
        state: present

    - name: Delete compute image volume
      openstack.cloud.volume:
        name: "{{ volumes_info.volumes[0].id }}"
        state: absent

    - debug:
        msg: "Created {{ compute_node_image }}."
