- hosts: localhost
  gather_facts: false
  vars_files: 
    - ./vars/main.yml

  tasks:
    - name: Find all cluster instances
      openstack.cloud.server_info:
        server: "{{ cluster_name }}*"
      register: cluster_instances

    - name: Delete all cluster instances
      openstack.cloud.server:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ cluster_instances.openstack_servers }}"

    - name: Delete all cluster volumes
      openstack.cloud.volume:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ cluster_instances.openstack_servers }}"

    - name: Delete compute node image volume
      openstack.cloud.volume:
         name: "{{ compute_node_image }}"
         state: absent

    - name: Delete compute node image
      openstack.cloud.image:
        name: "{{ compute_node_image }}"
        state: absent

    - debug:
        msg: "Cleaned up {{ cluster_name }} cloud resources." 
