---
- name: Get head node information
  openstack.cloud.server_info:
    server: "{{ head_node_name }}"
  register: headnode

- name: Add head node to Ansible inventory
  add_host:
    name: "{{ headnode.openstack_servers[0].private_v4 }}"
    groups: headnode
    ansible_user: "{{ image_init_user }}"
    ansible_ssh_private_key_file: "{{ ssh_private_keyfile }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand='ssh -W %h:%p -q {{ proxy_user }}@{{ proxy_server }} -i {{ proxy_private_keyfile }}'"
    ansible_python_interpreter: /usr/bin/python3
  changed_when: false
